# A list Nvidia docker images.
# https://hub.docker.com/r/nvidia/cuda/tags
FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04
#FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

ENV DEBIAN_FRONTEND=noninteractive

# Copy installers.
COPY installers /tmp/installers

# Run root level installs.
RUN bash /tmp/installers/install.sh

# Define environment variables.
ENV USERNAME yxie

# Change user.
USER $USERNAME
WORKDIR /home/$USERNAME

# User level commands.
RUN bash /tmp/installers/post_install.sh